import {
	AtSignIcon,
	BellIcon,
	InfoIcon,
	MoonIcon,
	QuestionIcon,
	StarIcon,
	UnlockIcon,
} from "@chakra-ui/icons";

export const CriptoCoins = [
	{ id: "01coin", symbol: "zoc", name: "01coin", icon: <MoonIcon /> },
	{ id: "0chain", symbol: "zcn", name: "Zus", icon: <StarIcon /> },
	{ id: "0x", symbol: "zrx", name: "0x", icon: <UnlockIcon /> },
	{ id: "0xcert", symbol: "zxc", name: "0xcert", icon: <QuestionIcon /> },
	{ id: "0xdao", symbol: "oxd", name: "0xDAO", icon: <InfoIcon /> },
	{ id: "0xdao-v2", symbol: "oxd v2", name: "0xDAO V2", icon: <BellIcon /> },
	{ id: "01coin", symbol: "zoc", name: "01coin", icon: <MoonIcon /> },
	{ id: "0chain", symbol: "zcn", name: "Zus", icon: <StarIcon /> },
	{ id: "0x", symbol: "zrx", name: "0x", icon: <UnlockIcon /> },
	{ id: "0xcert", symbol: "zxc", name: "0xcert", icon: <QuestionIcon /> },
	{ id: "0xdao", symbol: "oxd", name: "0xDAO", icon: <InfoIcon /> },
	{ id: "0xdao-v2", symbol: "oxd v2", name: "0xDAO V2", icon: <BellIcon /> },
	{ id: "01coin", symbol: "zoc", name: "01coin", icon: <MoonIcon /> },
	{ id: "0chain", symbol: "zcn", name: "Zus", icon: <StarIcon /> },
	{ id: "0x", symbol: "zrx", name: "0x", icon: <UnlockIcon /> },
	{ id: "0xcert", symbol: "zxc", name: "0xcert", icon: <QuestionIcon /> },
	{ id: "0xdao", symbol: "oxd", name: "0xDAO", icon: <InfoIcon /> },
	{ id: "0xdao-v2", symbol: "oxd v2", name: "0xDAO V2", icon: <BellIcon /> },
];
